// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Status_Bar1;
extern lv_obj_t * ui_label_wifi1;
extern lv_obj_t * ui_label_mqtt1;
extern lv_obj_t * ui_EmotionCircle1;
extern lv_obj_t * ui_uiEmotionLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

