// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Status_Bar1 = NULL;
lv_obj_t * ui_label_wifi1 = NULL;
lv_obj_t * ui_label_mqtt1 = NULL;
lv_obj_t * ui_EmotionCircle1 = NULL;
lv_obj_t * ui_uiEmotionLabel1 = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Status_Bar1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_height(ui_Status_Bar1, 57);
    lv_obj_set_width(ui_Status_Bar1, lv_pct(84));
    lv_obj_set_x(ui_Status_Bar1, -19);
    lv_obj_set_y(ui_Status_Bar1, -128);
    lv_obj_set_align(ui_Status_Bar1, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Status_Bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Status_Bar1, lv_color_hex(0xE5EBEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Status_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_wifi1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_label_wifi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_wifi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_wifi1, -38);
    lv_obj_set_y(ui_label_wifi1, -128);
    lv_obj_set_align(ui_label_wifi1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_label_wifi1, "[  ]");
    lv_obj_set_style_text_color(ui_label_wifi1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_wifi1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_wifi1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_mqtt1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_label_mqtt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_mqtt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_mqtt1, 44);
    lv_obj_set_y(ui_label_mqtt1, -128);
    lv_obj_set_align(ui_label_mqtt1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label_mqtt1, "[  ] ");
    lv_obj_set_style_text_color(ui_label_mqtt1, lv_color_hex(0x706E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_mqtt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_mqtt1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EmotionCircle1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_EmotionCircle1, 80);
    lv_obj_set_height(ui_EmotionCircle1, 80);
    lv_obj_set_x(ui_EmotionCircle1, -2);
    lv_obj_set_y(ui_EmotionCircle1, -19);
    lv_obj_set_align(ui_EmotionCircle1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EmotionCircle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EmotionCircle1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EmotionCircle1, lv_color_hex(0xCBEF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmotionCircle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiEmotionLabel1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_uiEmotionLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uiEmotionLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_uiEmotionLabel1, 0);
    lv_obj_set_y(ui_uiEmotionLabel1, -31);
    lv_obj_set_align(ui_uiEmotionLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiEmotionLabel1, "...");
    lv_obj_set_style_text_color(ui_uiEmotionLabel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiEmotionLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiEmotionLabel1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Status_Bar1 = NULL;
    ui_label_wifi1 = NULL;
    ui_label_mqtt1 = NULL;
    ui_EmotionCircle1 = NULL;
    ui_uiEmotionLabel1 = NULL;

}
